service: my-first-service

# app and org for use with dashboard.serverless.com
app: my-first-app
org: jorobowallace

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    sourcemaps: true
    caching: true
    stats: false
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  environment:
    API_KEY: 8c64ccbdcf6e407cae8b857c8d22e096


# outputs:
#   custom-output: any-value-here

# you can define service wide environment variables here



functions:
  team-bye:
    handler: handlers/byeWeek.byeWeek
  standings:
    handler: handlers/standings.standings
